### ISSUE TITLE
correspondence between texture feature and pointcloud

### ISSUE THREAD

**Issue by hwb0314** [photoneo/phoxi_camera#11]
Hello,
I am using a phoxi M scanner, and I want to extract feature points on the gray texture image. However, I don't know how to get the correspondent depth value of the extracted features. Could you give me some suggestions?

**Comment by marcelsvec** [comment]
Hello, sorry for the delayed response. 

The output from the PhoXi 3D Scanner can contain point cloud, depth map and texture information. The correspondence between texture and depth map is direct, the pixel at position [x,y] in texture has the depth that is at the same position in depth map.

The correspondence to the point cloud is described on the wiki page: http://wiki.photoneo.com/index.php/Point_Cloud_Topology

Let us know if more explanation is needed. Thank you

**Comment by tiexuedanxin** [comment]
> Hello, sorry for the delayed response.
> 
> The output from the PhoXi 3D Scanner can contain point cloud, depth map and texture information. The correspondence between texture and depth map is direct, the pixel at position [x,y] in texture has the depth that is at the same position in depth map.
> 
> The correspondence to the point cloud is described on the wiki page: http://wiki.photoneo.com/index.php/Point_Cloud_Topology
> 
> Let us know if more explanation is needed. Thank you
hello, Is need not to concern the image distortion of the gray texture image, Or the distortion is too small that can be ignore?
