### ISSUE TITLE
Add Phoxi Camera Xacro files

### ISSUE THREAD

**Issue by durovsky** [photoneo/phoxi_camera#4]
In order to simplify implementation of robotic cells with PhoXi scanners, it would be very convenient if ready to use xacro files for all available scanner sizes would be included within this package. See Kinect Xacro for inspiration: 

ROS Answers: http://answers.ros.org/question/110151/kinect-urdf/
Kinect URDF XACRO: https://github.com/turtlebot/turtlebot/blob/hydro/turtlebot_description/urdf/sensors/kinect.urdf.xacro

**Comment by najlepsiwebdesigner** [comment]
Hi Feri! Is this what you required in this issue? https://github.com/photoneo/phoxi_camera/commit/556f04c1f75ad000960f4c3475c99d25b7ea4fb7

**Comment by durovsky** [comment]
Exactly, thank you for adding these
