### ISSUE TITLE
Empty rostopics 

### ISSUE THREAD

**Issue by yswi** [photoneo/phoxi_camera#58]
Hi
I'm using Ubuntu 20.04 with ROS-noetic.
I can successfully build the package but I can't echo any rostopics except for /phoxi_camera/parameter_descriptions.

Below is what I get after running **rostest -t phoxi_camera phoxi_camera_ros_interfaces.test**
Is this from the incompatibility between ROS-noetic and the phoxi_camera package? 

... logging to /home/ /.ros/log/rostest-young-PC-55422.log
testRosInterfaces (rostest.runner.RosTest) ... [ROSTEST]setup[/home/ /catkin_phoxi/src/phoxi_camera/test/launch/phoxi_camera_ros_interfaces.test] run_id[342cba26-1728-11ec-befa-63f39d70b74e] starting
started roslaunch server http://~~

SUMMARY
========

PARAMETERS
 * /phoxi_camera/ambient_light_suppression: False
 * /phoxi_camera/camera_only_mode: False
 * /phoxi_camera/confidence: 3.0
 * /phoxi_camera/coordinate_space: 1
 * /phoxi_camera/frame_id: PhoXi3Dscanner_se...
 * /phoxi_camera/init_from_config: False
 * /phoxi_camera/latch_topics: False
 * /phoxi_camera/organized_cloud: True
 * /phoxi_camera/resolution: 1
 * /phoxi_camera/scan_multiplier: 1
 * /phoxi_camera/scanner_id: JHE-129
 * /phoxi_camera/send_confidence_map: True
 * /phoxi_camera/send_depth_map: True
 * /phoxi_camera/send_normal_map: True
 * /phoxi_camera/send_point_cloud: True
 * /phoxi_camera/send_texture: True
 * /phoxi_camera/shutter_multiplier: 1
 * /phoxi_camera/single_pattern_exposure: 2
 * /phoxi_camera/timeout: -3
 * /phoxi_camera/topic_queue_size: 1
 * /phoxi_camera/trigger_mode: 1
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /
    phoxi_camera (phoxi_camera/phoxi_camera)

[ROSTEST]setup[/home/ /catkin_phoxi/src/phoxi_camera/test/launch/phoxi_camera_ros_interfaces.test] run_id[342cba26-1728-11ec-befa-63f39d70b74e] done
[ROSTEST]Running test [RosInterfaces]
ROS_MASTER_URI=
setting /run_id to 342cba26-1728-11ec-befa-63f39d70b74e
process[phoxi_camera-1]: started with pid [55438]
[ROSTEST]running test RosInterfaces
process[RosInterfaces-2]: started with pid [55439]
test_connect_disconnectCamera (__main__.Test_phoxi_camera_ros_interface) ... [ INFO] [1631822198.883382465]: Connected to JHE-129
ok
test_getDeviceList (__main__.Test_phoxi_camera_ros_interface) ... Achievable cameras, you can check them, it must be equal to reality:
['JHE-129', 'InstalledExamples-basic-example']
ok
test_getFrame (__main__.Test_phoxi_camera_ros_interface) ... [ WARN] [1631822209.301927510]: Empty confidence map!
FAIL
test_getHardwareIdentification (__main__.Test_phoxi_camera_ros_interface) ... ok
test_getSupportedCapturingModes (__main__.Test_phoxi_camera_ros_interface) ... ok
test_isAcquiring (__main__.Test_phoxi_camera_ros_interface) ... ok
test_isAcquiringV2 (__main__.Test_phoxi_camera_ros_interface) ... ok
test_isConnected (__main__.Test_phoxi_camera_ros_interface) ... ok
test_isConnectedV2 (__main__.Test_phoxi_camera_ros_interface) ... ok
test_saveFrame (__main__.Test_phoxi_camera_ros_interface) ... [ INFO] [1631822248.166480168]: path: /home/young/.ros/file.ply
ok
test_saveLastFrameV2 (__main__.Test_phoxi_camera_ros_interface) ... [ INFO] [1631822256.376415935]: File path: /home/young/.ros/file.ply
[ INFO] [1631822257.055804412]: File path: /home/ /.ros/file.praw
[ INFO] [1631822257.153079302]: File path: /home/ /.ros/file.ptx
ok
test_setCoordianteSpace (__main__.Test_phoxi_camera_ros_interface) ... ok
test_setTransformation (__main__.Test_phoxi_camera_ros_interface) ... ok
test_startAcquisition (__main__.Test_phoxi_camera_ros_interface) ... ok
test_startAcquisitionV2 (__main__.Test_phoxi_camera_ros_interface) ... ok
test_stopAcquisition (__main__.Test_phoxi_camera_ros_interface) ... ok
test_stopAcquisitionV2 (__main__.Test_phoxi_camera_ros_interface) ... ok
test_triggerImage (__main__.Test_phoxi_camera_ros_interface) ... ok

======================================================================
FAIL: test_getFrame (__main__.Test_phoxi_camera_ros_interface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/< some directory>/catkin_phoxi/src/phoxi_camera/test/interfaces/test_phoxi_camera_ros_interfaces.py", line 210, in test_getFrame
    assert published_topics_num == 4, "Some topic was not published after get_frame service"
AssertionError: Some topic was not published after get_frame service

----------------------------------------------------------------------
Ran 18 tests in 87.129s

FAILED (failures=1)
-------------------------------------------------------------
SUMMARY:
 * RESULT: FAIL
 * TESTS: 18
 * ERRORS: 0 []
 * FAILURES: 1 [test_getFrame]

[RosInterfaces-2] process has died [pid 55439, exit code 1, cmd /home/young/catkin_phoxi/src/phoxi_camera/test/interfaces/test_phoxi_camera_ros_interfaces.py --gtest_output=xml:/home/young/.ros/test_results/phoxi_camera/rosunit-RosInterfaces.xml --text __name:=RosInterfaces __log:=/home/young/.ros/log/342cba26-1728-11ec-befa-63f39d70b74e/RosInterfaces-2.log].
log file: /home/young/.ros/log/342cba26-1728-11ec-befa-63f39d70b74e/RosInterfaces-2*.log
[ROSTEST]test [RosInterfaces] finished
[ROSTEST][ROSTEST] test [RosInterfaces] done
[ROSTEST]tearDown[/home/<some directory>/catkin_phoxi/src/phoxi_camera/test/launch/phoxi_camera_ros_interfaces.test]
shutting down processing monitor...
[phoxi_camera-1] killing on exit
... shutting down processing monitor complete
[ROSTEST]rostest teardown /home/<some directory>/catkin_phoxi/src/phoxi_camera/test/launch/phoxi_camera_ros_interfaces.test complete
ok

----------------------------------------------------------------------
Ran 1 test in 89.370s

OK

**Comment by neerja123-gupta** [comment]
Hello,
I am facing the same problem. Were you able to solve it?

Thanks

**Comment by yswi** [comment]
yes, please try $ rosservice call /phoxi_camera/get_frame "in_: -1"

**Comment by yswi** [comment]
I haven't run the example afterwards, but I figured out an alternative way to call the service  "get_frame". 
Please try $ rosservice call /phoxi_camera/get_frame "in_: -1" instead.
